name: icon-badge-action
description: icon add badge action
author: 'https://github.com/srz-zumix'

inputs:
  glob:
    description: 'icon file paths glob pattern (Default: CURRENT_PATH/**/*.appiconset/*.{png,PNG})'
    default: ''
  dark:
    description: dark mode
    default: false
  grayscale:
    description: make the icon grayscale
    default: false
  alpha_channel:
    description: keep alpha channel
    default: false
  alpha:
    description: add alpha badge
    default: false
  beta:
    description: add beta badge
    default: false
  shield:
    description: add shield static badge string
    default: ''
  shield_geometry:
    description: add shield static badge geometry
    default: ''
  shield_scale:
    description: add shield static badge scale
    default: ''
  shield_no_resize:
    description: add shield static badge no resize
    default: false
  docker_image_tag:
    description: 'Docker image tag'
    default: ''

runs:
  using: "composite"
  steps:
  - name: Check docker
    id: check-docker
    shell: bash {0}
    run: |
      which docker
      echo "exit-code=$?" >> "${GITHUB_OUTPUT}"
    if: runner.os == 'macos'
  - uses: douglascamata/setup-docker-macos-action@v1-alpha
    if: runner.os == 'macos' && steps.check-docker.outputs.exit-code != '0'
  # - uses: docker/setup-buildx-action@v3
  # - uses: docker/build-push-action@v5
  #   id: docker-build
  #   with:
  #     context: ${{ github.action_path }}/docker
  #     file: ${{ github.action_path }}/docker/Dockerfile
  #     push: false
  #     load: true
  #     cache-from: type=gha
  #     cache-to: type=gha,mode=max

  - name: Resolve Docker image tag
    id: docker
    shell: bash
    env:
      ACTION_REF: ${{ github.action_ref }}
      TAGNAME: ${{ inputs.docker_image_tag }}
    run: |
      CACHE_KEY="${ACTION_REF:-}"
      if [ -z "${TAGNAME}" ]; then
        if [[ "${ACTION_REF:-}" =~ v[0-9]+ ]]; then
          TAGNAME="${ACTION_REF#v}"
        else
          TAGNAME=latest
        fi
      fi
      {
        echo "imagename=ghcr.io/srz-zumix/icon-badge-action"
        echo "tagname=${TAGNAME}"
        echo "cachekey=${CACHE_KEY:-${TAGNAME}}"
        echo "cachepath=local_image_cache"
      } >> "${GITHUB_OUTPUT}"
  - name: Cache Docker image
    id: cache-image
    uses: actions/cache@v4
    with:
      path: ${{ steps.docker.outputs.cachepath }}
      key: ${{ runner.os }}-icon-badge-action-${{ steps.docker.outputs.cachekey }}
  - name: Pull and save Docker image
    shell: bash
    env:
      IMAGE_ID: ${{ steps.docker.outputs.imagename }}:${{ steps.docker.outputs.tagname }}
    run: |
      docker pull ${IMAGE_ID}
      docker save ${IMAGE_ID} -o ${{ steps.docker.outputs.cachepath }}
    if: steps.cache-image.outputs.cache-hit != 'true'
  - name: Load Docker image
    shell: bash
    run: |
      docker load -i ${{ steps.docker.outputs.cachepath }}
  - name: Run icon-badge-action
    shell: bash
    env:
      INPUT_GLOB: ${{ inputs.glob }}
      INPUT_DARK: ${{ inputs.dark }}
      INPUT_GRAYSCALE: ${{ inputs.grayscale }}
      INPUT_ALPHA_CHANNEL: ${{ inputs.alpha_channel }}
      INPUT_ALPHA: ${{ inputs.alpha }}
      INPUT_BETA: ${{ inputs.beta }}
      INPUT_SHIELD: ${{ inputs.shield }}
      INPUT_SHIELD_GEOMETRY: ${{ inputs.shield_geometry }}
      INPUT_SHIELD_SCALE: ${{ inputs.shield_scale }}
      INPUT_SHIELD_NO_RESIZE: ${{ inputs.shield_no_resize }}
      # IMAGE_ID: ${{ steps.docker-build.outputs.imageid }}
      IMAGE_ID: ${{ steps.docker.outputs.imagename }}:${{ steps.docker.outputs.tagname }}
    run: |
      docker run --rm -v ${{ github.workspace }}:/github/workspace -w /github/workspace \
        -e INPUT_GLOB \
        -e INPUT_DARK \
        -e INPUT_GRAYSCALE \
        -e INPUT_ALPHA_CHANNEL \
        -e INPUT_ALPHA \
        -e INPUT_BETA \
        -e INPUT_SHIELD \
        -e INPUT_SHIELD_GEOMETRY \
        -e INPUT_SHIELD_SCALE \
        -e INPUT_SHIELD_NO_RESIZE \
        -e GITHUB_WORKSPACE=/github/workspace \
        "${IMAGE_ID}"

branding:
  icon: edit
  color: orange
