name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  test-docker-action:
    name: Docker Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Checkout test data
        uses: actions/checkout@v5
        with:
          repository: HazAT/badge
          path: badge
      - name: Copy icons
        run: |
          mkdir -p test/assets
          cp badge/assets/*fitrack.png test/assets/icon_fitrack_alpha.png

      - name: Test Local Action (Alpha)
        uses: ./docker
        with:
          glob: "${{ github.workspace }}/test/assets/*_alpha.png"
          alpha: true

      - uses: actions/upload-artifact@v4
        with:
          name: test-results-docker
          path: test/assets/*.png

  test-action:
    name: GitHub Actions Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          # - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      REF_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Checkout test data
        uses: actions/checkout@v5
        with:
          repository: HazAT/badge
          path: badge
      - name: Copy icons
        run: |
          mkdir -p test/assets
          cp badge/assets/*fitrack.png test/assets/icon_fitrack_alpha.png
          cp badge/assets/*175x175.png test/assets/icon_beta.png
          cp badge/assets/*fitrack.png test/assets/icon_fitrack_beta.png
          cp badge/assets/*fitrack.png test/assets/icon_fitrack_shield.png
          cp badge/assets/*fitrack.png test/assets/icon_fitrack_shield_arrange.png
          cp badge/assets/*fitrack.png test/assets/icon_fitrack_shield_with_badge.png
          cp badge/assets/*fitrack.png test/assets/icon_fitrack_grayscale.png

      - name: Test Local Action (Alpha)
        uses: ./
        with:
          glob: "${{ github.workspace }}/test/assets/*_alpha.png"
          alpha: true

      - name: Test Local Action (Beta)
        uses: ./
        with:
          glob: test/assets/*_beta.png
          beta: true

      - name: Test Local Action (shield)
        uses: ./
        with:
          glob: test/assets/*_shield.png
          shield: "icon--badge--action-${{ env.REF_NAME }}-blue"

      - name: Test Local Action (shield arrange)
        uses: ./
        with:
          glob: test/assets/*_shield_arrange.png
          shield: "icon--badge--action-${{ env.REF_NAME }}-green"
          shield_geometry: "+0+25%"
          shield_scale: 0.75

      - name: Test Local Action (shield and badge)
        uses: ./
        with:
          glob: test/assets/*_with_badge.png
          shield: "icon--badge--action-${{ env.REF_NAME }}-red"
          beta: true

      - name: Test Local Action (Grayscale)
        uses: ./
        with:
          glob: test/assets/*_grayscale.png
          grayscale: true

      - uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: test/assets/*.png

  test-no-cache:
    name: Docker no cache Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Checkout test data
        uses: actions/checkout@v5
        with:
          repository: HazAT/badge
          path: badge
      - name: Copy icons
        run: |
          mkdir -p test/assets
          cp badge/assets/*175x175.png test/assets/icon_beta.png
          cp badge/assets/*fitrack.png test/assets/icon_fitrack_beta.png

      - name: Test Local Action (Alpha)
        uses: ./
        with:
          glob: test/assets/*_beta.png
          beta: true
          cache: false

      - uses: actions/upload-artifact@v4
        with:
          name: test-results-no-cache
          path: test/assets/*.png
