name: Update Semver
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        type: string
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

permissions:
  contents: write

jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: haya14busa/action-update-semver@7d2c558640ea49e798d46539536190aff8c18715 # v1.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag || '' }}
