name: Update Semver
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        type: string
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

permissions:
  contents: write

jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: haya14busa/action-update-semver@3f49a54b677d969c819c1c6ebea626a54dafe032 # v1.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag || '' }}
